USE priam_app;


ALTER TABLE PRIAM_CATCMS_PARTICIPANTS DROP FOREIGN KEY IF EXISTS FK_TYPE_CMS;
ALTER TABLE PRIAM_CATCMS_PARTICIPANTS DROP FOREIGN KEY IF EXISTS FK_IDE12;

ALTER TABLE PRIAM_CATCMS_CATALOGUE
  ADD 'ELIGIBLE_CREATION' TINYINT(0);

ALTER TABLE PRIAM_CATCMS_JOURNAL
  ADD 'TYPE_CMS' VARCHAR(3);

COMMIT;