USE priam_app;


ALTER TABLE PRIAM_CATCMS_PARTICIPANTS DROP FOREIGN KEY IF EXISTS FK_TYPE_CMS;
ALTER TABLE PRIAM_CATCMS_PARTICIPANTS DROP FOREIGN KEY IF EXISTS FK_IDE12;

ALTER TABLE PRIAM_CATCMS_CATALOGUE
  ADD 'ELIGIBLE_CREATION' TINYINT(0);

ALTER TABLE PRIAM_CATCMS_PARTICIPANTS
  ADD 'OEUVRE_SORTIE' TINYINT(0);

ALTER TABLE PRIAM_CATCMS_JOURNAL
  ADD 'TYPE_CMS' VARCHAR(3);


DROP TABLE IF EXISTS PRIAM_CATCMS_STATISTIQUES;
CREATE TABLE PRIAM_CATCMS_STATISTIQUES (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  TYPE_CMS VARCHAR(3),
  DATE DATE DEFAULT NULL,
  NOM_FICHIER VARCHAR(255),
  NB_OEUVRES bigint(20),
  NB_CREATION bigint(20),
  NB_RENOUVELLEMENT bigint(20),
  NB_TOTAL_OEUVRES bigint(20),
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

COMMIT;