USE priam_app;


ALTER TABLE PRIAM_CATCMS_PARTICIPANTS DROP FOREIGN KEY IF EXISTS FK_TYPE_CMS;
ALTER TABLE PRIAM_CATCMS_PARTICIPANTS DROP FOREIGN KEY IF EXISTS FK_IDE12;

ALTER TABLE PRIAM_CATCMS_CATALOGUE
  ADD 'ELIGIBLE_CREATION' TINYINT(0);

ALTER TABLE PRIAM_CATCMS_PARTICIPANTS
  ADD 'OEUVRE_SORTIE' TINYINT(0);

ALTER TABLE PRIAM_CATCMS_JOURNAL
  ADD 'TYPE_CMS' VARCHAR(3);

ALTER TABLE PRIAM_CATCMS_PARTICIPANTS
  ADD ID_CATALOGUE BIGINT(20) COMMENT 'ID OEUVRE TABLE CATALOGUE';

ALTER TABLE PRIAM_CATCMS_PARTICIPANTS
  ADD CONSTRAINT FK_ID_CATALOGUE
FOREIGN KEY (ID_CATALOGUE) REFERENCES PRIAM_CATCMS_CATALOGUE(ID);

COMMIT;