spring:
  profiles:
    active: @spring.active.profiles@
  jmx:
    enabled: false
  http:
    multipart:
      max-file-size: -1
endpoints:
  health:
    sensitive: false

management:
  security:
    enabled: false



