spring:
  profiles:
    active: @spring.active.profiles@
  jmx:
    enabled: false

mipsa:
  local: @mipsa.mode.local@

endpoints:
  health:
    sensitive: false

management:
  security:
    enabled: false