-- Habib Benmerzouka
USE priam_app;

DROP TABLE IF EXISTS PRIAM_FICHIER;
DROP TABLE IF EXISTS PRIAM_STATUT;
DROP TABLE IF EXISTS PRIAM_TYPUTIL;
DROP TABLE IF EXISTS PRIAM_FAMILLE_TYPUTIL;
DROP TABLE IF EXISTS PRIAM_LIGNE_PROGRAMME;



CREATE TABLE PRIAM_STATUT (CODE VARCHAR(255) NOT NULL  DEFAULT 'EN_COURS', LIBELLE VARCHAR(255), DESCRIPTION VARCHAR(255),
PRIMARY KEY(CODE));

CREATE TABLE PRIAM_FAMILLE_TYPUTIL (

  CODE VARCHAR(255) NOT NULL  COMMENT 'Code Famille',
  LIBELLE VARCHAR(255) COMMENT 'Libelle du code',
  DESCRIPTION VARCHAR(255) COMMENT 'Description',
  PRIMARY KEY(CODE)

);

CREATE TABLE PRIAM_TYPUTIL (

  CODE VARCHAR(255) NOT NULL COMMENT 'Code Type Utilisation',
  CDE_FAMILLE VARCHAR(255) COMMENT 'Code Famille Type utilisation',
  LIBELLE VARCHAR(255) COMMENT 'Libelle du code',
  DESCRIPTION VARCHAR(255) COMMENT 'Description',

  CONSTRAINT FK_CDE_FAMILLE FOREIGN KEY (CDE_FAMILLE) REFERENCES PRIAM_FAMILLE_TYPUTIL(CODE),
  PRIMARY KEY(CODE)

);

CREATE TABLE PRIAM_FICHIER (
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  NOM varchar(255 ) DEFAULT NULL COMMENT 'Nom du fichier',
  FAMILLE VARCHAR (255) COMMENT 'Famille',
  TYPE_UTIL VARCHAR (255) COMMENT 'Type utilisation',
  DATE_DEBUT_CHGT DATETIME COMMENT 'Dete de Debut de chargement',
  DATE_FIN_CHGT DATETIME COMMENT 'Dete de Fin de chargement',
  NB_LIGNES BIGINT COMMENT 'Nombre de lignes dans le fichier',
  STATUT_CODE VARCHAR(255) COMMENT 'Statcd primut du fichier',

 -- CONSTRAINT FK_STATUT FOREIGN KEY (STATUT_CODE) REFERENCES PRIAM_STATUT(CODE),
 -- CONSTRAINT FK_FAMILLE FOREIGN KEY (FAMILLE) REFERENCES PRIAM_FAMILLE_TYPUTIL(CODE),
 -- CONSTRAINT FK_TYPE_UTIL FOREIGN KEY (TYPE_UTIL) REFERENCES PRIAM_TYPUTIL(CODE),
  PRIMARY KEY(ID)
);


CREATE TABLE PRIAM_LIGNE_PROGRAMME (
  `id` int(11) AUTO_INCREMENT NOT NULL,
  `cdeCisac` varchar(3) DEFAULT NULL,
  `cdeTer` bigint(20) DEFAULT NULL,
  `rionEffet` int(11) DEFAULT NULL,
  `cdeFamilTypUtil` varchar(45) DEFAULT NULL,
  `cdeModFac` varchar(45) DEFAULT NULL,
  `numProg` int(11) DEFAULT NULL,
  `keyLigPenel` int(11) DEFAULT NULL,
  `cdeUtil` varchar(45) DEFAULT NULL,
  `cdeTypUtil` varchar(45) DEFAULT NULL,
  `cdeTypProg` varchar(45) DEFAULT NULL,
  `cdeCompl` varchar(45) DEFAULT NULL,
  `libProg` varchar(100) DEFAULT NULL,
  `compLibProg` varchar(100) DEFAULT NULL,
  `datDbtProg` datetime DEFAULT NULL,
  `datFinProg` datetime DEFAULT NULL,
  `hrDbt` int(11) DEFAULT NULL,
  `hrFin` int(11) DEFAULT NULL,
  `cdeGreDif` varchar(45) DEFAULT NULL,
  `cdeModDif` varchar(45) DEFAULT NULL,
  `cdeTypIde12` varchar(45) DEFAULT NULL,
  `ide12` bigint(20) DEFAULT NULL,
  `datDif` datetime DEFAULT NULL,
  `hrDif` int(11) DEFAULT NULL,
  `durDif` int(11) DEFAULT NULL,
  `nbrDif` int(11) DEFAULT NULL,
  `mt` double DEFAULT NULL,
  `ctna` varchar(45) DEFAULT NULL,
  `paramCoefHor` varchar(10) DEFAULT NULL,
  `durDifCtna` int(11) DEFAULT NULL,
  `cdeLng` varchar(45) DEFAULT NULL,
  `indDoubSsTit` varchar(45) DEFAULT NULL,
  `tax` double DEFAULT NULL,
  `typMt` varchar(45) DEFAULT NULL,

  PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
