USE priam_app;

ALTER TABLE PRIAM_CATCMS_PARTICIPANTS
  ADD 'OEUVRE_SORTIE' TINYINT(0);


DROP TABLE IF EXISTS PRIAM_CATCMS_PARTICIPANTS_SAVE;
CREATE TABLE PRIAM_CATCMS_PARTICIPANTS_SAVE (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  TYPE_CMS VARCHAR(3),
  IDE12 bigint(20) DEFAULT NULL,
  ROLE VARCHAR(2),
  PARTICIPANT VARCHAR(255),
  OEUVRE_SORTIE TINYINT(0),

  PRIMARY KEY (ID)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PRIAM_CATCMS_PARTICIPANTS_DELETE;
CREATE TABLE PRIAM_CATCMS_PARTICIPANTS_DELETE (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  TYPE_CMS VARCHAR(3),
  IDE12 bigint(20) DEFAULT NULL,
  ROLE VARCHAR(2),
  PARTICIPANT VARCHAR(255),
  OEUVRE_SORTIE TINYINT(0),

  PRIMARY KEY (ID)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/*DROP VIEW IF EXISTS PRIAM_CATCMS_CATALOGUE_VIEW ;
create view PRIAM_CATCMS_CATALOGUE_VIEW as
  SELECT CAT.ID AS ID, CAT.IDE12 AS IDE12, CAT.TYPE_CMS AS TYPE_CMS, CAT.TITRE AS TITRE,
    CAT.TYP_UTIL_GEN, CAT.DATE_ENTREE, CAT.TYPE_INSCRIPTION, CAT.DATE_RENOUVELLEMENT, CAT.DATE_SORTIE, CAT.TYPE_SORTIE,
    CAT.RAISON_SORTIE,
        substring_index(GROUP_CONCAT(PART.ROLE  ORDER BY PART.ID ASC SEPARATOR ',' ), ',', 4) AS ROLES,
        substring_index(GROUP_CONCAT(PART.PARTICIPANT  ORDER BY PART.ID ASC SEPARATOR ','), ',', 4) AS PARTICIPANTS,
    CAT.ELIGIBLE_CREATION

  FROM PRIAM_CATCMS_PARTICIPANTS PART
    INNER JOIN PRIAM_CATCMS_CATALOGUE CAT ON CAT.TYPE_CMS=PART.TYPE_CMS AND CAT.IDE12=PART.IDE12
    WHERE PART.OEUVRE_SORTIE = 0
  GROUP BY CAT.IDE12, CAT.TYPE_CMS;*/


COMMIT;