USE priam_app;

ALTER TABLE PRIAM_CATCMS_PARTICIPANTS
  ADD 'OEUVRE_SORTIE' TINYINT(0);


DROP TABLE IF EXISTS PRIAM_CATCMS_PARTICIPANTS_SAVE;
CREATE TABLE PRIAM_CATCMS_PARTICIPANTS_SAVE (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  TYPE_CMS VARCHAR(3),
  IDE12 bigint(20) DEFAULT NULL,
  ROLE VARCHAR(2),
  PARTICIPANT VARCHAR(255),
  OEUVRE_SORTIE TINYINT(0),

  PRIMARY KEY (ID)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PRIAM_CATCMS_PARTICIPANTS_DELETE;
CREATE TABLE PRIAM_CATCMS_PARTICIPANTS_DELETE (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  TYPE_CMS VARCHAR(3),
  IDE12 bigint(20) DEFAULT NULL,
  ROLE VARCHAR(2),
  PARTICIPANT VARCHAR(255),
  OEUVRE_SORTIE TINYINT(0),

  PRIMARY KEY (ID)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;



COMMIT;