USE priam_app;

INSERT INTO `PRIAM_STATUT` (`CODE`, `LIBELLE`) VALUES ('CHARGEMENT_KO','Chargement KO');
INSERT INTO `PRIAM_STATUT` (`CODE`, `LIBELLE`) VALUES ('CHARGEMENT_OK','Chargement OK');
INSERT INTO `PRIAM_STATUT` (`CODE`, `LIBELLE`) VALUES ('EN_COURS','En cours');