USE priam_app;

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CP MODIFY COLUMN durDif BIGINT(20);
ALTER TABLE PRIAM_LIGNE_PROGRAMME_CP MODIFY COLUMN durDifEdit BIGINT(20);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CP MODIFY COLUMN nbrDif BIGINT(20);
ALTER TABLE PRIAM_LIGNE_PROGRAMME_CP MODIFY COLUMN nbrDifEdit BIGINT(20);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS MODIFY COLUMN nbrDif BIGINT(20);
ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS MODIFY COLUMN nbrDifEdit BIGINT(20);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS_COPY MODIFY COLUMN nbrDif BIGINT(20);

commit;

