DROP TABLE IF EXISTS PRIAM_CATCMS_CATALOGUE;

CREATE TABLE PRIAM_CATCMS_CATALOGUE (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  TYPE_CMS VARCHAR(3),
  IDE12 bigint(20) DEFAULT NULL,
  TITRE VARCHAR(255),
  TYP_UTIL_GEN VARCHAR(255),
  DATE_ENTREE DATE DEFAULT NULL,
  TYPE_INSCRIPTION VARCHAR(255),
  DATE_RENOUVELLEMENT DATE DEFAULT NULL,
  DATE_SORTIE DATE DEFAULT NULL,
  TYPE_SORTIE VARCHAR(255),
  RAISON_SORTIE VARCHAR(255),
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS PRIAM_CATCMS_PARTICIPANTS;
CREATE TABLE PRIAM_CATCMS_PARTICIPANTS (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  TYPE_CMS VARCHAR(3),
  IDE12 bigint(20) DEFAULT NULL,
  ROLE VARCHAR(2),
  PARTICIPANT VARCHAR(255),
  PRIMARY KEY (ID)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;