-- Habib Benmerzouka


-- ------------------------------------------
-- -------- TABLE PRIAM_STATUT --------------
-- ------------------------------------------
INSERT INTO PRIAM_STATUT
(CODE, LIBELLE, DESCRIPTION) VALUES
  ('EN_COURS', 'En cours', 'En cours de chargement');

INSERT INTO PRIAM_STATUT
(CODE, LIBELLE, DESCRIPTION) VALUES
  ('OK', 'OK', 'Chargement OK');

INSERT INTO PRIAM_STATUT
(CODE, LIBELLE, DESCRIPTION) VALUES
  ('KO', 'KO', 'Chargement KO');

INSERT INTO PRIAM_STATUT
(CODE, LIBELLE, DESCRIPTION) VALUES
  ('AFFECTE', 'Affecte', 'Fichier Affecte');

INSERT INTO PRIAM_STATUT
(CODE, LIBELLE, DESCRIPTION) VALUES
  ('ABONDONNE', 'Abondonne', 'Fichier Abondonne.');

-- ---------------------------------------------------
-- ------ TABLE PRIAM_LIBFAMITYPUTIL --------------
-- -------------------------------------------------
INSERT INTO PRIAM_LIBFAMITYPUTIL (CODE, LIBELLE, CDELNG) VALUES
  ('COPIEPRIV', 'Copie Privée', 'FR');

INSERT INTO PRIAM_LIBFAMITYPUTIL
(CODE, LIBELLE, CDELNG) VALUES
  ('FDSVAL', 'Valorisation', 'FR');

INSERT INTO PRIAM_LIBFAMITYPUTIL
(CODE, LIBELLE, CDELNG) VALUES
  ('CMS', 'CMS', 'FR');

-- ---------------------------------------------------
-- ------ TABLE PRIAM_LIBTYPUTIL ------------------------
-- ---------------------------------------------------
INSERT INTO PRIAM_LIBTYPUTIL (CODE, LIBELLE, CDELNG)
VALUES ('CPRIVSONPH', 'Copie privée sonore Phono', 'FR');

INSERT INTO PRIAM_LIBTYPUTIL (CODE, LIBELLE, CDELNG)
VALUES ('CPRIVAUDV', 'Copie Privée Audiovisuelle', 'FR');

INSERT INTO PRIAM_LIBTYPUTIL (CODE, LIBELLE, CDELNG)
VALUES ('CPRIVSONRD', 'Copie Privée Sonore radio', 'FR');

INSERT INTO PRIAM_LIBTYPUTIL (CODE, LIBELLE, CDELNG)
VALUES ('COPRIVSON', 'Copie Privée Sonore', 'FR');

INSERT INTO PRIAM_LIBTYPUTIL (CODE, LIBELLE, CDELNG)
VALUES ('CPRIVAUDPL', 'Copie Privée Audiovisuel - Part Littéraire', 'FR');

INSERT INTO PRIAM_LIBTYPUTIL (CODE, LIBELLE, CDELNG)
VALUES ('CPRIVSONPH', 'Private copy sound (PHONO)', 'EN');

INSERT INTO PRIAM_LIBTYPUTIL (CODE, LIBELLE, CDELNG)
VALUES ('CPRIVAUDV', 'Private copy audiovisual', 'EN');

INSERT INTO PRIAM_LIBTYPUTIL (CODE, LIBELLE, CDELNG)
VALUES ('CPRIVSONRD', 'Private copy sound', 'EN');

INSERT INTO PRIAM_LIBTYPUTIL (CODE, LIBELLE, CDELNG)
VALUES ('COPRIVSON', 'Copie Privée Sonore', 'EN');

INSERT INTO PRIAM_LIBTYPUTIL (CODE, LIBELLE, CDELNG)
VALUES ('PRIME', 'Prime', 'FR');

INSERT INTO PRIAM_LIBTYPUTIL (CODE, LIBELLE, CDELNG)
VALUES ('VALORIS', 'Fonds de valorisation', 'FR');

INSERT INTO PRIAM_LIBTYPUTIL (CODE, LIBELLE, CDELNG)
VALUES ('ENCOURG', 'Encouragement', 'FR');

-- ---------------------------------------------------
-- ------ TABLE PRIAM_FAMILTYPUTIL -------------------
-- ---------------------------------------------------
INSERT INTO PRIAM_FAMILTYPUTIL (CDEFAMILTYPUTIL, DATDBTVLD, DATFINVLD)
VALUES ('COPIEPRIV', CURDATE(), NULL);

INSERT INTO PRIAM_FAMILTYPUTIL (CDEFAMILTYPUTIL, DATDBTVLD, DATFINVLD)
VALUES ('FDSVAL', CURDATE(), NULL);

INSERT INTO PRIAM_FAMILTYPUTIL (CDEFAMILTYPUTIL, DATDBTVLD, DATFINVLD)
VALUES ('CMS', CURDATE(), NULL);

-- ---------------------------------------------------
-- ------ TABLE PRIAM_TYPUTIL -------------------
-- ---------------------------------------------------
INSERT INTO PRIAM_TYPUTIL (CDETYPUTIL, CDEFAMILTYPUTIL, DATDBTVLD, DATFINVLD)
VALUES ('CPRIVSONPH', 'COPIEPRIV', CURDATE(), NULL);

INSERT INTO PRIAM_TYPUTIL (CDETYPUTIL, CDEFAMILTYPUTIL, DATDBTVLD, DATFINVLD)
VALUES ('CPRIVAUDV', 'COPIEPRIV', CURDATE(), NULL);

INSERT INTO PRIAM_TYPUTIL (CDETYPUTIL, CDEFAMILTYPUTIL, DATDBTVLD, DATFINVLD)
VALUES ('CPRIVSONRD', 'COPIEPRIV', CURDATE(), NULL);

INSERT INTO PRIAM_TYPUTIL (CDETYPUTIL, CDEFAMILTYPUTIL, DATDBTVLD, DATFINVLD)
VALUES ('COPRIVSON', 'COPIEPRIV', CURDATE(), NULL);

INSERT INTO PRIAM_TYPUTIL (CDETYPUTIL, CDEFAMILTYPUTIL, DATDBTVLD, DATFINVLD)
VALUES ('CPRIVAUDPL', 'COPIEPRIV', CURDATE(), NULL);

INSERT INTO PRIAM_TYPUTIL (CDETYPUTIL, CDEFAMILTYPUTIL, DATDBTVLD, DATFINVLD)
VALUES ('PRIME', 'FDSVAL', CURDATE(), NULL);

INSERT INTO PRIAM_TYPUTIL (CDETYPUTIL, CDEFAMILTYPUTIL, DATDBTVLD, DATFINVLD)
VALUES ('VALORIS', 'FDSVAL', CURDATE(), NULL);


INSERT INTO PRIAM_TYPUTIL (CDETYPUTIL, CDEFAMILTYPUTIL, DATDBTVLD, DATFINVLD)
VALUES ('ENCOURG', 'CMS', CURDATE(), NULL);


INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('Fichier 01', 'COPIEPRIV', 'COPRIVSON', '2017-02-04 17:15:14', NULL, 3000, 'EN_COURS');

INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('Fichier 02', 'COPIEPRIV', 'COPRIVSON', '2017-02-03 17:15:14', NULL, 9500, 'EN_COURS');


INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('Fichier 03', 'COPIEPRIV', 'COPRIVSON', '2017-02-01 17:15:14', NULL, 6500, 'EN_COURS');


INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('Fichier 04', 'COPIEPRIV', 'COPRIVSON', '2017-04-01 17:15:14', NULL, 1478, 'EN_COURS');


INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('Fichier 05', 'COPIEPRIV', 'COPRIVSON', '2017-05-01 17:10:14', NULL, 7451, 'EN_COURS');


INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('Fichier 06', 'COPIEPRIV', 'COPRIVSON', '2017-05-02 18:15:14', NULL, 15000, 'EN_COURS');


INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('Fichier 08', 'COPIEPRIV', 'COPRIVSON', '2017-02-01 17:15:14', NULL, 6500, 'EN_COURS');


INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('Fichier 09', 'COPIEPRIV', 'COPRIVSON', '2017-04-01 17:15:14', '2017-04-01 22:10:11', 22000, 'CHARGEMENT_OK');


INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('Fichier 11', 'COPIEPRIV', 'COPRIVSON', '2017-05-01 17:10:14', '2017-05-02 01:10:00', 45789, 'CHARGEMENT_OK');


INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('Fichier 12', 'COPIEPRIV', 'COPRIVSON', '2017-05-02 18:15:14', '2017-05-01 18:50:04', 15000, 'CHARGEMENT_KO');


INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('Fichier 13', 'COPIEPRIV', 'COPRIVSON', '2017-05-04 18:15:14', '2017-05-04 22:57:04', 15000, 'CHARGEMENT_KO');



INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('FF_PENEF_EXTRANA_EXTCPRIVSONPH_MON_FICHIER2', 'COPIEPRIV', 'COPRIVSON', '2017-04-01 17:15:14', '2017-04-01 22:10:11', 22000, 'CHARGEMENT_OK');

INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE)
VALUES ('FF_PENEF_EXTRANA_EXTCPRIVSONRD_20170406140540', 'COPIEPRIV', 'COPRIVSON', '2017-04-01 17:15:14', '2017-04-01 22:10:11', 22000, 'CHARGEMENT_OK');