DROP TABLE IF EXISTS PRIAM_CATCMS_RDO;
DROP TABLE IF EXISTS PRIAM_CATCMS_STATUT;
DROP TABLE IF EXISTS PRIAM_CATCMS_FICHIER;
DROP TABLE IF EXISTS PRIAM_CATCMS_FICHIER_LOG;
DROP TABLE IF EXISTS PRIAM_CATCMS_JOURNAL;
DROP TABLE IF EXISTS PRIAM_CATCMS_CATALOGUE;
DROP TABLE IF EXISTS PRIAM_CATCMS_PENEF;
DROP TABLE IF EXISTS PRIAM_CATCMS_STATISTIQUES;
DROP TABLE IF EXISTS PRIAM_CATCMS_PARTICIPANTS;



CREATE TABLE PRIAM_CATCMS_RDO (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  TYPE_CMS VARCHAR(3) COMMENT 'FR poour France et ANF pour Antilles',
  IDE12 bigint(20) DEFAULT NULL COMMENT 'Code oeuvre RDO',
  TITRE VARCHAR(255) COMMENT 'titre oeuvre RDO',
  TYP_UTIL_GEN VARCHAR(255) COMMENT 'type utilisation RDO',
  DATE_CATAL DATE DEFAULT NULL COMMENT 'date catalogue RDO',
  ROLE VARCHAR(255) COMMENT 'role RDO',
  PARTICIPANT VARCHAR(255) COMMENT 'participant RDO',
  POURCENTAGE_DP TINYINT(4) COMMENT 'pourcentage DP',
  PRIMARY KEY (ID)
);


CREATE TABLE PRIAM_CATCMS_STATUT (
  CODE varchar(255) NOT NULL DEFAULT 'EN_COURS',
  LIBELLE varchar(255) DEFAULT NULL,
  CONSTRAINT PRIAM_CATCMS_STATUT_PK PRIMARY KEY (CODE)
);


CREATE TABLE PRIAM_CATCMS_FICHIER (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NOM varchar(255) DEFAULT NULL,
  DATE_DEBUT_CHGT datetime DEFAULT NULL,
  DATE_FIN_CHGT datetime DEFAULT NULL,
  NB_LIGNES bigint(20) DEFAULT NULL,
  STATUT_CODE varchar(255) DEFAULT NULL,
  TYPE_FICHIER varchar(25) DEFAULT NULL,
  CONSTRAINT PRIAM_CATCMS_FICHIER_PK PRIMARY KEY (ID),
  CONSTRAINT FK_STATUT_CATCMS_CODE FOREIGN KEY (STATUT_CODE) REFERENCES PRIAM_CATCMS_STATUT (CODE)
);


CREATE TABLE PRIAM_CATCMS_FICHIER_LOG (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  ID_FICHIER bigint(20) DEFAULT NULL,
  LOG varchar(1024) DEFAULT NULL,
  DATE datetime DEFAULT NULL,
  CONSTRAINT PRIAM_CATCMS_FICHIER_LOG_PK PRIMARY KEY (ID),
  CONSTRAINT ID_CATCMS_FICHIER_FK FOREIGN KEY (ID_FICHIER) REFERENCES PRIAM_CATCMS_FICHIER (ID)
);


CREATE TABLE PRIAM_CATCMS_JOURNAL (
  ID int(11) NOT NULL AUTO_INCREMENT,
  EVENEMENT varchar(100) DEFAULT NULL,
  IDE12 bigint(20) DEFAULT NULL,
  DATE datetime DEFAULT CURRENT_TIMESTAMP,
  UTILISATEUR varchar(255) DEFAULT NULL,
  TYPE_CMS VARCHAR(3),
  CONSTRAINT PRIAM_CATCMS_JOURNAL_PK PRIMARY KEY (ID)
);

CREATE TABLE PRIAM_CATCMS_PENEF (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  TYPE_CMS VARCHAR(3),
  IDE12 bigint(20) DEFAULT NULL,
  CDE_TYP_IDE12 VARCHAR(255),
  CDE_TYP_UTIL_ORI VARCHAR(255),
  TITRE_OEUVRE VARCHAR(255),
  ROLE_PARTICIPANT1 VARCHAR(255) ,
  NOM_PARTICIPANT1 VARCHAR(255),
  ID_FICHIER bigint(20) DEFAULT NULL,

  PRIMARY KEY (ID),

  CONSTRAINT `FK_ID_FICHIER_PENEF` FOREIGN KEY (ID_FICHIER) REFERENCES PRIAM_CATCMS_FICHIER(ID)
);

CREATE TABLE PRIAM_CATCMS_CATALOGUE (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  TYPE_CMS VARCHAR(3),
  IDE12 bigint(20) DEFAULT NULL,
  TITRE VARCHAR(255),
  TYP_UTIL_GEN VARCHAR(255),
  DATE_ENTREE DATE DEFAULT NULL,
  TYPE_INSCRIPTION VARCHAR(255),
  DATE_RENOUVELLEMENT DATE DEFAULT NULL,
  DATE_SORTIE DATE DEFAULT NULL,
  TYPE_SORTIE VARCHAR(255),
  RAISON_SORTIE VARCHAR(255),
  PARTICIPANTS TEXT,
  ROLES VARCHAR(255),
  ELIGIBLE_CREATION TINYINT(0),
  PRIMARY KEY (ID)
);

CREATE TABLE PRIAM_CATCMS_STATISTIQUES (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  TYPE_CMS VARCHAR(3),
  DATE DATE DEFAULT NULL,
  NOM_FICHIER VARCHAR(255),
  NB_OEUVRES bigint(20),
  NB_CREATION bigint(20),
  NB_RENOUVELLEMENT bigint(20),
  NB_TOTAL_OEUVRES bigint(20),
  PRIMARY KEY (ID));

  CREATE TABLE PRIAM_CATCMS_PARTICIPANTS (
  ID bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'identifiant technique',
  TYPE_CMS VARCHAR(3),
  IDE12 bigint(20) DEFAULT NULL,
  ROLE VARCHAR(2),
  PARTICIPANT VARCHAR(255),
  OEUVRE_SORTIE TINYINT(0),
  PRIMARY KEY (ID)
);