USE priam_app;

INSERT INTO PRIAM_PROGRAMME(NUMPROG, NOM, RION_THEORIQUE, CDEFAMILTYPUTIL, CDETYPUTIL, TYPE_REPART, DATE_CREATION, STATUT_PROG_CODE, RION_PAIEMENT)
VALUES ('180001', 'Programme 180001', 619, 'UC','SONOFRA', 'OEUVRE', CURDATE(), 'CREE', NULL);

INSERT INTO PRIAM_PROGRAMME(NUMPROG, NOM, RION_THEORIQUE, CDEFAMILTYPUTIL, CDETYPUTIL, TYPE_REPART, DATE_CREATION, STATUT_PROG_CODE, RION_PAIEMENT)
VALUES ('180002', 'Programme 180002', 619, 'UC','SONOANT', 'OEUVRE', CURDATE(), 'CREE', NULL);


INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE, NUMPROG)
VALUES ('Fichier 150', 'UC', 'SONOFRA', '2018-01-22 10:33:18', '2018-01-22 10:33:19', 5, 'CHARGEMENT_OK', NULL);

INSERT INTO PRIAM_FICHIER
(NOM, CDEFAMILTYPUTIL, CDETYPUTIL, DATE_DEBUT_CHGT, DATE_FIN_CHGT, NB_LIGNES, STATUT_CODE, NUMPROG)
VALUES ('Fichier 151', 'UC', 'SONOANT', '2018-01-22 10:33:18', '2018-01-22 10:33:19', 5, 'CHARGEMENT_OK', NULL);

INSERT INTO PRIAM_LIGNE_PROGRAMME_CMS (numProg, cdeTypUtil, ide12, nbrDif, ID_FICHIER, titreOeuvre, roleParticipant1, nomParticipant1, ajout)
VALUES ('180001', 'SONOFRA', 2000163011, 30, (SELECT ID FROM PRIAM_FICHIER WHERE NOM ='Fichier 150'), 'Titre1', 'CA', 'Participant1', 'AUTOMATIQUE');

INSERT INTO PRIAM_LIGNE_PROGRAMME_CMS (numProg, cdeTypUtil, ide12, nbrDif, ID_FICHIER, titreOeuvre, roleParticipant1, nomParticipant1, ajout)
VALUES ('180002', 'SONOANT', 2002037711, 30, (SELECT ID FROM PRIAM_FICHIER WHERE NOM ='Fichier 151'), 'Titre2', 'CA', 'Participant2', 'AUTOMATIQUE');


COMMIT;
