INSERT INTO PRIAM_CATCMS_STATUT (`CODE`, `LIBELLE`) VALUES ('CHARGEMENT_KO','Chargement KO');
INSERT INTO PRIAM_CATCMS_STATUT (`CODE`, `LIBELLE`) VALUES ('CHARGEMENT_OK','Chargement OK');
INSERT INTO PRIAM_CATCMS_STATUT (`CODE`, `LIBELLE`) VALUES ('EN_COURS','En cours');


INSERT INTO PRIAM_CATCMS_FICHIER (NOM, DATE_DEBUT_CHGT, NB_LIGNES, STATUT_CODE, TYPE_FICHIER)
VALUES ('FF_OCTAV_CATALOGUE_ANF', '2018-05-07 11:04:48', 2, 'EN_COURS', 'ANF');

INSERT INTO PRIAM_CATCMS_FICHIER (NOM, DATE_DEBUT_CHGT, NB_LIGNES, STATUT_CODE, TYPE_FICHIER)
VALUES ('FF_OCTAV_CATALOGUE_FR', '2018-05-09 11:04:48', 2, 'EN_COURS', 'FR');
