DROP TABLE IF EXISTS PRIAM_CATCMS_RDO;
DROP TABLE IF EXISTS PRIAM_CATCMS_STATUT;
DROP TABLE IF EXISTS PRIAM_CATCMS_FICHIER;
DROP TABLE IF EXISTS PRIAM_CATCMS_FICHIER_LOG;
DROP TABLE IF EXISTS PRIAM_CATCMS_JOURNAL;



CREATE TABLE PRIAM_CATCMS_RDO (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  TYPE_CMS VARCHAR(3),
  IDE12 bigint(20) DEFAULT NULL,
  TITRE VARCHAR(255),
  TYP_UTIL_GEN VARCHAR(255),
  DATE_ENTREE datetime DEFAULT NULL,
  TYPE_INSCRIPTION VARCHAR(255),
  DATE_RENOUVELLEMENT datetime DEFAULT NULL,
  POURCENTAGE_DP TINYINT(4),
  DATE_SORTIE datetime DEFAULT NULL,
  TYPE_SORTIE VARCHAR(255),
  ROLE VARCHAR(255),
  PARTICIPANT VARCHAR(255),
  CONSTRAINT PRIAM_CATCMS_RDO_PK PRIMARY KEY (ID)
);


CREATE TABLE PRIAM_CATCMS_STATUT (
  CODE varchar(255) NOT NULL DEFAULT 'EN_COURS',
  LIBELLE varchar(255) DEFAULT NULL,
  CONSTRAINT PRIAM_CATCMS_STATUT_PK PRIMARY KEY (CODE)
);


CREATE TABLE PRIAM_CATCMS_FICHIER (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NOM varchar(255) DEFAULT NULL,
  DATE_DEBUT_CHGT datetime DEFAULT NULL,
  DATE_FIN_CHGT datetime DEFAULT NULL,
  NB_LIGNES bigint(20) DEFAULT NULL,
  STATUT_CODE varchar(255) DEFAULT NULL,
  TYPE_FICHIER varchar(25) DEFAULT NULL,
  CONSTRAINT PRIAM_CATCMS_FICHIER_PK PRIMARY KEY (ID),
  CONSTRAINT FK_STATUT_CATCMS_CODE FOREIGN KEY (STATUT_CODE) REFERENCES PRIAM_CATCMS_STATUT (CODE)
);


CREATE TABLE PRIAM_CATCMS_FICHIER_LOG (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  ID_FICHIER bigint(20) DEFAULT NULL,
  LOG varchar(1024) DEFAULT NULL,
  DATE datetime DEFAULT NULL,
  CONSTRAINT PRIAM_CATCMS_FICHIER_LOG_PK PRIMARY KEY (ID),
  CONSTRAINT ID_CATCMS_FICHIER_FK FOREIGN KEY (ID_FICHIER) REFERENCES PRIAM_CATCMS_FICHIER (ID)
);


CREATE TABLE PRIAM_CATCMS_JOURNAL (
  ID int(11) NOT NULL AUTO_INCREMENT,
  EVENEMENT varchar(100) DEFAULT NULL,
  IDE12 bigint(20) DEFAULT NULL,
  DATE datetime DEFAULT CURRENT_TIMESTAMP,
  UTILISATEUR varchar(255) DEFAULT NULL,
  CONSTRAINT PRIAM_CATCMS_JOURNAL_PK PRIMARY KEY (ID)
);