package fr.sacem.priam.model.domain.fv;

public enum StatutEnrichissementFV {

    TO_SRV_OCTAV_CTNU,
    IN_SRV_OCTAV_CTNU,
    DONE_SRV_OCTAV_CTNU,
    TO_SRV_INFO_OEUVRE,
    IN_SRV_INFO_OEUVRE,
    DONE_SRV_INFO_OEUVRE,
    TO_SRV_AD_CLES_PROTECTION,
    IN_SRV_AD_CLES_PROTECTION,
    DONE_SRV_AD_CLES_PROTECTION,
    TO_SRV_AD_INFO,
    IN_SRV_AD_INFO,
    DONE_SRV_AD_INFO,
    ERROR_SRV_ENRICHISSEMENT
}
