INSERT INTO PRIAM_CATCMS_CATALOGUE (TYPE_CMS, IDE12, TITRE, TYP_UTIL_GEN, DATE_ENTREE, TYPE_INSCRIPTION, DATE_SORTIE, TYPE_SORTIE)
VALUES ('FR', 10000111, 'PAI OPO', 'PHONOFR', '2008-06-20', 'Automatique', null, null);
INSERT INTO PRIAM_CATCMS_CATALOGUE (TYPE_CMS, IDE12, TITRE, TYP_UTIL_GEN, DATE_ENTREE, TYPE_INSCRIPTION, DATE_RENOUVELLEMENT, DATE_SORTIE, TYPE_SORTIE)
VALUES ('FR', 2000001411, 'TANDIS QUE J AGONISE', 'PHONOFR', '2001-06-20', 'Automatique', '2002-01-01',null , null);
INSERT INTO PRIAM_CATCMS_CATALOGUE (TYPE_CMS, IDE12, TITRE, TYP_UTIL_GEN, DATE_ENTREE, TYPE_INSCRIPTION, DATE_SORTIE, TYPE_SORTIE)
VALUES ('FR', 2000002411, 'GRACEFUL BAMBOO', 'PHONOFR', '2028-06-20', 'Automatique', null, null);
INSERT INTO PRIAM_CATCMS_CATALOGUE (TYPE_CMS, IDE12, TITRE, TYP_UTIL_GEN, DATE_ENTREE, TYPE_INSCRIPTION, DATE_RENOUVELLEMENT, DATE_SORTIE, TYPE_SORTIE)
VALUES ('FR', 2000012511, 'DES PIEDS ET DES MAINS', 'PHONOFR', '2028-06-20', 'Automatique', '2038-06-20', null, null);

INSERT INTO PRIAM_CATCMS_CATALOGUE (TYPE_CMS, IDE12, TITRE, TYP_UTIL_GEN, DATE_ENTREE, TYPE_INSCRIPTION, DATE_SORTIE, TYPE_SORTIE)
VALUES ('ANF', 2000014011, 'BOUCHERIE DE L AVENIR', 'PHONOFR', '2001-06-20', 'Automatique', null, null);
INSERT INTO PRIAM_CATCMS_CATALOGUE (TYPE_CMS, IDE12, TITRE, TYP_UTIL_GEN, DATE_ENTREE, TYPE_INSCRIPTION, DATE_SORTIE, TYPE_SORTIE)
VALUES ('ANF', 2000013811, 'POCO TANGO UN POCO PASO MUC', 'PHONOFR', '2018-06-20', 'Automatique', null, null);
INSERT INTO PRIAM_CATCMS_CATALOGUE (TYPE_CMS, IDE12, TITRE, TYP_UTIL_GEN, DATE_ENTREE, TYPE_INSCRIPTION, DATE_RENOUVELLEMENT, DATE_SORTIE, TYPE_SORTIE)
VALUES ('ANF', 2632785011, 'LA BOHEME', 'PHONOFR', '2001-06-20', 'Automatique', '2006-06-20', null, null);
INSERT INTO PRIAM_CATCMS_CATALOGUE (TYPE_CMS, IDE12, TITRE, TYP_UTIL_GEN, DATE_ENTREE, TYPE_INSCRIPTION, DATE_RENOUVELLEMENT, DATE_SORTIE, TYPE_SORTIE)
VALUES ('ANF', 6035521211, 'DANS LE PORT D AMSTERDAM', 'PHONOFR', '2027-06-20', 'Automatique', '2028-06-20', null, null);
