USE priam_app;

DROP TABLE IF EXISTS PRIAM_ETAT_OEUVRE;
CREATE TABLE PRIAM_ETAT_OEUVRE (
  CDE_ETAT VARCHAR(50) NOT NULL,
  LIB_ETAT VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (CDE_ETAT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS
ADD CONSTRAINT FK_CDE_ETAT
FOREIGN KEY (AJOUT) REFERENCES PRIAM_ETAT_OEUVRE(CDE_ETAT);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS_COPY
ADD CONSTRAINT FK_CDE_ETAT2
FOREIGN KEY (AJOUT) REFERENCES PRIAM_ETAT_OEUVRE(CDE_ETAT);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_TRAITEMENT_BATCH
  ADD CONSTRAINT FK_CDE_ETAT3
FOREIGN KEY (AJOUT) REFERENCES PRIAM_ETAT_OEUVRE(CDE_ETAT);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CP
  ADD CONSTRAINT FK_CDE_ETAT4
FOREIGN KEY (AJOUT) REFERENCES PRIAM_ETAT_OEUVRE(CDE_ETAT);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CP
    ADD `durDifEdit` int(11) DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection';

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CP
  ADD `nbrDifEdit` int(11) DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection';


ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS
  ADD `mtEdit` double DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection';

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS
  ADD `nbrDifEdit` int(11) DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection';


DROP TABLE IF EXISTS PRIAM_JOURNAL_EVENEMENT;
CREATE TABLE PRIAM_JOURNAL_EVENEMENT (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `numprog` varchar(8) NOT NULL,
  `evenement` varchar(100) DEFAULT NULL,
  `ide12` bigint(20) DEFAULT NULL,
  `date` datetime DEFAULT CURRENT_TIMESTAMP,
  `utilisateur` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS PRIAM_SITUATION_AVANT;
CREATE TABLE PRIAM_SITUATION_AVANT (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SITUATION` varchar(455) DEFAULT NULL,
  `ID_EVENEMENT` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS PRIAM_SITUATION_APRES;
CREATE TABLE PRIAM_SITUATION_APRES (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SITUATION` varchar(455) DEFAULT NULL,
  `ID_EVENEMENT` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PRIAM_SITUATION_AVANT
  ADD CONSTRAINT FK_JOURNAL_EVENEMENT
FOREIGN KEY (ID_EVENEMENT) REFERENCES PRIAM_JOURNAL_EVENEMENT(ID);

ALTER TABLE PRIAM_SITUATION_APRES
  ADD CONSTRAINT FK_JOURNAL_EVENEMENT2
FOREIGN KEY (ID_EVENEMENT) REFERENCES PRIAM_JOURNAL_EVENEMENT(ID);

commit;

