USE priam_app;

DROP TABLE IF EXISTS PRIAM_ETAT_OEUVRE;
CREATE TABLE PRIAM_ETAT_OEUVRE (
  CDE_ETAT VARCHAR(50) NOT NULL,
  LIB_ETAT VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (CDE_ETAT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS
ADD CONSTRAINT FK_CDE_ETAT
FOREIGN KEY (AJOUT) REFERENCES PRIAM_ETAT_OEUVRE(CDE_ETAT);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS_COPY
ADD CONSTRAINT FK_CDE_ETAT2
FOREIGN KEY (AJOUT) REFERENCES PRIAM_ETAT_OEUVRE(CDE_ETAT);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_TRAITEMENT_BATCH
  ADD CONSTRAINT FK_CDE_ETAT3
FOREIGN KEY (AJOUT) REFERENCES PRIAM_ETAT_OEUVRE(CDE_ETAT);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CP
    ADD `durDifEdit` int(11) DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection';

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CP
  ADD `nbrDifEdit` int(11) DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection';

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS
  ADD `mtEdit` double DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection';

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS
  ADD `nbrDifEdit` int(11) DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection';


commit;