USE priam_app;

INSERT INTO `PRIAM_ELIGIBILITE_STATUT_PROGRAMME` (`CODE`, `LIBELLE`) VALUES ('EN_COURS_DESAFFECTATION',' En cours de desaffectation');
INSERT INTO `PRIAM_ELIGIBILITE_STATUT_PROGRAMME` (`CODE`, `LIBELLE`) VALUES ('FIN_DESAFFECTATION','Fin de desaffectation');
INSERT INTO `PRIAM_ELIGIBILITE_STATUT_PROGRAMME` (`CODE`, `LIBELLE`) VALUES ('ERREUR_ELIGIBILITE','Erreur Traitement eligibilite');
INSERT INTO `PRIAM_ELIGIBILITE_STATUT_PROGRAMME` (`CODE`, `LIBELLE`) VALUES ('ERREUR_DESAFFECTATION','Erreur Desaffectation');

INSERT INTO PRIAM_ETAT_OEUVRE (CDE_ETAT, LIB_ETAT) VALUES ('AUTOMATIQUE', 'Automatique');
INSERT INTO PRIAM_ETAT_OEUVRE (CDE_ETAT, LIB_ETAT) VALUES ('MANUEL', 'Manuel');
INSERT INTO PRIAM_ETAT_OEUVRE (CDE_ETAT, LIB_ETAT) VALUES ('CORRIGE', 'Corrigé');

COMMIT;

