USE priam_app;

DROP TABLE IF EXISTS PRIAM_ETAT_OEUVRE;
CREATE TABLE PRIAM_ETAT_OEUVRE (
  CDE_ETAT VARCHAR(50) NOT NULL,
  LIB_ETAT VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (CDE_ETAT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS
ADD CONSTRAINT FK_CDE_ETAT
FOREIGN KEY (AJOUT) REFERENCES PRIAM_ETAT_OEUVRE(CDE_ETAT);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS_COPY
ADD CONSTRAINT FK_CDE_ETAT2
FOREIGN KEY (AJOUT) REFERENCES PRIAM_ETAT_OEUVRE(CDE_ETAT);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_TRAITEMENT_BATCH
  ADD CONSTRAINT FK_CDE_ETAT3
FOREIGN KEY (AJOUT) REFERENCES PRIAM_ETAT_OEUVRE(CDE_ETAT);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CP
  ADD CONSTRAINT FK_CDE_ETAT4
FOREIGN KEY (AJOUT) REFERENCES PRIAM_ETAT_OEUVRE(CDE_ETAT);

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CP
    ADD `durDifEdit` int(11) DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection';

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CP
  ADD `nbrDifEdit` int(11) DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection';


ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS
  ADD `mtEdit` double DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection';

ALTER TABLE PRIAM_LIGNE_PROGRAMME_CMS
  ADD `nbrDifEdit` int(11) DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection';


DROP TABLE IF EXISTS PRIAM_JOURNAL_EVENEMENT;
CREATE TABLE PRIAM_JOURNAL_EVENEMENT (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `numprog` varchar(8) NOT NULL,
  `evenement` varchar(100) DEFAULT NULL,
  `ide12` bigint(20) DEFAULT NULL,
  `date` datetime DEFAULT CURRENT_TIMESTAMP,
  `utilisateur` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS PRIAM_SITUATION_AVANT;
CREATE TABLE PRIAM_SITUATION_AVANT (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SITUATION` varchar(455) DEFAULT NULL,
  `ID_EVENEMENT` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS PRIAM_SITUATION_APRES;
CREATE TABLE PRIAM_SITUATION_APRES (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SITUATION` varchar(455) DEFAULT NULL,
  `ID_EVENEMENT` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE PRIAM_SITUATION_AVANT
  ADD CONSTRAINT FK_JOURNAL_EVENEMENT
FOREIGN KEY (ID_EVENEMENT) REFERENCES PRIAM_JOURNAL_EVENEMENT(ID);

ALTER TABLE PRIAM_SITUATION_APRES
  ADD CONSTRAINT FK_JOURNAL_EVENEMENT2
FOREIGN KEY (ID_EVENEMENT) REFERENCES PRIAM_JOURNAL_EVENEMENT(ID);


DROP TABLE IF EXISTS `PRIAM_LIGNE_PROGRAMME_CP_COPY`;
CREATE TABLE `PRIAM_LIGNE_PROGRAMME_CP_COPY` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cdeCisac` varchar(3) DEFAULT NULL,
  `cdeFamilTypUtil` varchar(45) DEFAULT NULL,
  `numProg` int(11) DEFAULT NULL,
  `cdeUtil` varchar(45) DEFAULT NULL,
  `cdeTypUtil` varchar(45) DEFAULT NULL,
  `cdeGreDif` varchar(45) DEFAULT NULL,
  `cdeModDif` varchar(45) DEFAULT NULL,
  `cdeTypIde12` varchar(45) DEFAULT NULL,
  `ide12` bigint(20) DEFAULT NULL,
  `durDif` int(11) DEFAULT NULL,
  `nbrDif` int(11) DEFAULT NULL,
  `libelleUtilisateur` varchar(255) DEFAULT NULL,
  `mt` double DEFAULT NULL,
  `ctna` varchar(45) DEFAULT NULL,
  `paramCoefHor` varchar(10) DEFAULT NULL,
  `durDifCtna` int(11) DEFAULT NULL,
  `cdeLng` varchar(45) DEFAULT NULL,
  `indDoubSsTit` varchar(45) DEFAULT NULL,
  `tax` double DEFAULT NULL,
  `typMt` varchar(45) DEFAULT NULL,
  `ID_FICHIER` bigint(20) DEFAULT NULL,
  `cdeGreIde12Cmplx` varchar(45) DEFAULT NULL,
  `cdeGreIde12` varchar(45) DEFAULT NULL,
  `titreAltOeuvPereCmplx` varchar(250) DEFAULT NULL,
  `titreAltPppalCmplx` varchar(250) DEFAULT NULL,
  `titreOriOeuvPereCmplx` varchar(250) DEFAULT NULL,
  `titreOriCmplx` varchar(250) DEFAULT NULL,
  `titreOeuvre` varchar(250) DEFAULT NULL,
  `cdePaysOriIso4NCmplx` varchar(45) DEFAULT NULL,
  `realisateurCmplx` varchar(250) DEFAULT NULL,
  `roleParticipant1` varchar(250) DEFAULT NULL,
  `nomParticipant1` varchar(250) DEFAULT NULL,
  `cdeTypUtilOri` varchar(45) DEFAULT NULL,
  `cdeFamilTypUtilOri` varchar(45) DEFAULT NULL,
  `utilisateur` varchar(250) DEFAULT 'Batch Extraction',
  `date_insertion` datetime DEFAULT CURRENT_TIMESTAMP,
  `ajout` varchar(45) DEFAULT 'AUTOMATIQUE',
  `selection` tinyint(1) DEFAULT '0',
  `idOeuvreManuel` int(11) DEFAULT NULL,
  `SEL_EN_COURS` tinyint(4) DEFAULT '1',
  `durDifEdit` int(11) DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection',
  `nbrDifEdit` int(11) DEFAULT NULL COMMENT  'Colonne qui sert pour le tableau editable dans ecran selection',
  PRIMARY KEY (`id`),
  KEY `FK_ID_FICHIER_CP_COPY` (`ID_FICHIER`),
  KEY `IDX_CDE_UTIL_CP_COPY` (`cdeUtil`),
  CONSTRAINT `FK_ID_FICHIER_CP_COPY` FOREIGN KEY (`ID_FICHIER`) REFERENCES `PRIAM_FICHIER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


commit;

